version: "3.1"
services:

  database:
    build:
      context: ./dev-db
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: root
    container_name: resolver-db
    expose:
      - '3306'
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10




