version: "3.1"
services:
  resolver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: resolver-api
    environment:
      NODE_ENV: production
    command: yarn run serve






