version: "3.1"
services:
  resolver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app/
    container_name: resolver-api
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - database

  database:
    build:
      context: ./dev-db
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: root
    container_name: resolver-db
    volumes:
      - ./dev-db/persistent_storage:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - 3306:3306




