version: "3.1"
services:
  resolver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: resolver-api
    environment:
      NODE_ENV: production
    command: "bash -c 'npx redocly build-docs ./specs/spec.yml -o ./specs/public/index.html && npx tsc && npx tsc-alias && npx cpy specs/* .env.* ./dist && NODE_ENV=production node -r tsconfig-paths/register dist/src/server.js'"








