/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/articles": {
    /** Get all the QR entries */
    get: {
      responses: {
        /** @description A list of IDs and URls */
        200: {
          content: {
            "application/json": components["schemas"]["QR"][];
          };
        };
      };
    };
    /** Create a new QR code */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["QRInput"];
        };
      };
      responses: {
        /** @description The created QR */
        201: {
          content: {
            "application/json": components["schemas"]["QR"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    QR: {
      id: string;
      url: string;
    };
    QRInput: {
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
