/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/docs': {
        /**
         * Get API documentation.
         * @description Serves the documentation for this service.
         */
        get: operations['serveDocs']
    }
    '/{id}': {
        /** Go to the final location of the entry specified by the {id} */
        get: {
            parameters: {
                path: {
                    /** @description Numeric ID of the entry to resolve */
                    codeId: number
                }
            }
            responses: {
                /** @description Go to the URL pointed by the entry code */
                302: {
                    content: never
                }
                404: components['responses']['404']
            }
        }
        /** Modify an existing entry. If the entry in question does not exist, one will be created */
        put: {
            parameters: {
                path: {
                    /** @description Numeric ID of the entry */
                    codeId: number
                }
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['EntryUrl']
                }
            }
            responses: {
                /** @description Modified entry */
                200: {
                    content: {
                        'application/json': components['schemas']['EntryFull']
                    }
                }
                /** @description The created entry */
                201: {
                    content: {
                        'application/json': components['schemas']['EntryFull']
                    }
                }
                400: components['responses']['400']
                404: components['responses']['404']
            }
        }
        /** Delete an entry */
        delete: {
            parameters: {
                path: {
                    /** @description Numeric ID of the entry */
                    codeId: number
                }
            }
            responses: {
                /** @description Code has been deleted */
                204: {
                    content: never
                }
                404: components['responses']['404']
            }
        }
    }
    '/': {
        /** Get all the entries */
        get: {
            responses: {
                /** @description A list of IDs and URls */
                200: {
                    content: {
                        'application/json': components['schemas']['EntryFull'][]
                    }
                }
            }
        }
        /** Create a new entry */
        post: {
            requestBody: {
                content: {
                    'application/json': components['schemas']['EntryUrl']
                }
            }
            responses: {
                /** @description The created entry */
                201: {
                    content: {
                        'application/json': components['schemas']['EntryFull']
                    }
                }
                400: components['responses']['400']
                404: components['responses']['404']
            }
        }
    }
}

export type webhooks = Record<string, never>

export interface components {
    schemas: {
        EntryFull: {
            id: number
            url: string
        }
        EntryUrl: {
            url: string
        }
        '4xxBody': {
            message?: string
            errors: {
                message?: string
            }[]
        }
    }
    responses: {
        /** @description Bad request. */
        400: {
            content: {
                'application/problem+json': components['schemas']['4xxBody']
            }
        }
        /** @description Unauthorized. */
        401: {
            content: {
                'application/problem+json': components['schemas']['4xxBody']
            }
        }
        /** @description Not Found. */
        404: {
            content: {
                'application/problem+json': components['schemas']['4xxBody']
            }
        }
    }
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
    /**
     * Get API documentation.
     * @description Serves the documentation for this service.
     */
    serveDocs: {
        responses: {
            /** @description OK. The API documentation. */
            200: {
                content: {
                    'text/html': string
                }
            }
        }
    }
}
