openapi: 3.0.0
info:
  title: Dynamic resolver redirection API
  description: A resolver that redirects to final destination URL based on the given gtin. Supports resolution, creation, deletion, and modification of entries
  version: 0.0.1
  license:
    name: ISC
    url: 'https://opensource.org/licenses/ISC'
  contact:
    name: Martijn Van Dooren
    email: martijn@tagshaper.com
security: []
paths:

  /docs:
    get:
      operationId: serveDocs
      x-eov-operation-handler: docs
      summary: Get API documentation.
      description: Serves the documentation for this service.
      responses:
        "200":
          description: OK. The API documentation.
          content:
            text/html:
              schema:
                type: string


  /01/{gtin}:
    get:
      summary: Go to the final location of the DigitalLink specified by the {gtin}
      x-eov-operation-id: resolveDigitalLinkByGtin
      x-eov-operation-handler: resolver 
      parameters:
        - in: path
          name: gtin
          schema:
            type: integer
          required: true
          description: Numeric gtin of the DigitalLink to resolve
      responses:
        '302':
          description: Go to the URL pointed by the DigitalLink code
        "404":
            $ref: "#/components/responses/404"

    delete:
      summary: Delete an DigitalLink
      x-eov-operation-id: deleteDigitalLinkByGtin
      x-eov-operation-handler: resolver 
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: gtin
          schema:
            type: integer
          required: true
          description: Numeric gtin of the DigitalLink
      responses:
        '204':
          description: Code has been deleted
        "401":
            $ref: "#/components/responses/401"
        "404":
            $ref: "#/components/responses/404"


    put:
      summary: Modify an existing DigitalLink. If the DigitalLink in question does not exist, one will be created
      x-eov-operation-id: updateDigitalLink
      x-eov-operation-handler: resolver 
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: gtin
          schema:
            type: integer
          required: true
          description: Numeric gtin of the DigitalLink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalLinkURL'

      responses:
        '200':
          description: Modified DigitalLink 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalLinkFull'
        '201':
          description: The created DigitalLink 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalLinkFull'
        "400":
            $ref: "#/components/responses/400"
        "401":
            $ref: "#/components/responses/401"
        "404":
            $ref: "#/components/responses/404"

  /01/{gtin}/21/{serialId}:
    get:
      summary: Go to the final location of the DigitalLink specified by the {gtin}
      x-eov-operation-id: resolveDigitalLinkBySerialId
      x-eov-operation-handler: resolver 
      parameters:
        - in: path
          name: gtin
          schema:
            type: integer
          required: true
          description: Numeric gtin of the DigitalLink to resolve
        - in: path
          name: serialId
          schema:
            type: integer
          required: true
          description: Numeric serialId of the DigitalLink to resolve
      responses:
        '302':
          description: Go to the URL pointed by the DigitalLink code
        "404":
            $ref: "#/components/responses/404"

  /:
    get:
      summary: Get all the entries
      x-eov-operation-id: getAllEntries
      x-eov-operation-handler: resolver
      responses:
        '200':
          description: A list of gtins and URls
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DigitalLinkFull'

    post:
      summary: Create a new DigitalLink
      x-eov-operation-id: createDigitalLink
      x-eov-operation-handler: resolver
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalLinkURL'
      responses:
        '201':
          description: The created DigitalLink
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalLinkFull'
        "400":
            $ref: "#/components/responses/400"
        "401":
            $ref: "#/components/responses/401"
        "404":
            $ref: "#/components/responses/404"




components:
  schemas:
    DigitalLinkFull:
      type: object
      properties:
        gtin:
          type: number
          format: int64
        destinationURL:
          type: string
      required:
        - gtin 
        - destinationURL 

    DigitalLinkURL:
      type: object
      properties:
        destinationURL:
          type: string
      required:
        - destinationURL

    "4xxBody":
      type: object
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            title: Error
            properties:
              message:
                type: string
      required: [errors]


  responses:
    "400":
      description: Bad request.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
    "401":
      description: Unauthorized.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
    "404":
      description: Not Found.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"

  securitySchemes:
      ApiKeyAuth:
        type: apiKey
        in: header
        name: X-API-KEY  
