openapi: 3.0.0
info:
  title: Dynamic resolver redirection API
  description: A resolver that redirects to final destination URL based on the given ID. Supports resolution, creation, deletion, and modification of entries
  version: 0.0.1
  license:
    name: ISC
    url: 'https://opensource.org/licenses/ISC'
  contact:
    name: Martijn Van Dooren
    email: martijn@tagshaper.com
security: []
paths:

  /docs:
    get:
      operationId: serveDocs
      x-eov-operation-handler: docs
      summary: Get API documentation.
      description: Serves the documentation for this service.
      responses:
        "200":
          description: OK. The API documentation.
          content:
            text/html:
              schema:
                type: string


  /{id}:
    get:
      summary: Go to the final location of the entry specified by the {id}
      x-eov-operation-id: resolveEntryById
      x-eov-operation-handler: resolver 
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the entry to resolve
      responses:
        '302':
          description: Go to the URL pointed by the entry code
        "404":
            $ref: "#/components/responses/404"

    delete:
      summary: Delete an entry
      x-eov-operation-id: deleteEntryById
      x-eov-operation-handler: resolver 
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the entry
      responses:
        '204':
          description: Code has been deleted
        "404":
            $ref: "#/components/responses/404"


    put:
      summary: Modify an existing entry. If the entry in question does not exist, one will be created
      x-eov-operation-id: updateEntry
      x-eov-operation-handler: resolver 
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryUrl'

      responses:
        '200':
          description: Modified entry 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryFull'
        '201':
          description: The created entry 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryFull'
        "400":
            $ref: "#/components/responses/400"
        "404":
            $ref: "#/components/responses/404"


  /:
    get:
      summary: Get all the entries
      x-eov-operation-id: getAllEntries
      x-eov-operation-handler: resolver
      responses:
        '200':
          description: A list of IDs and URls
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntryFull'

    post:
      summary: Create a new entry
      x-eov-operation-id: createEntry
      x-eov-operation-handler: resolver
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryUrl'
      responses:
        '201':
          description: The created entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryFull'
        "400":
            $ref: "#/components/responses/400"
        "404":
            $ref: "#/components/responses/404"




components:
  schemas:
    EntryFull:
      type: object
      properties:
        id:
          type: number
        url:
          type: string
      required:
        - id
        - url

    EntryUrl:
      type: object
      properties:
        url:
          type: string
      required:
        - url

    "4xxBody":
      type: object
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            title: Error
            properties:
              message:
                type: string
      required: [errors]


  responses:
    "400":
      description: Bad request.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
    "401":
      description: Unauthorized.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
    "404":
      description: Not Found.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"

  securitySchemes:
      ApiKeyAuth:
        type: apiKey
        in: header
        name: X-API-KEY  
