openapi: 3.0.0
info:
  title: Dynamic QR code redirection API
  version: 1.0.0
paths:
  /qrcode:
    get:
      summary: Get all the QR entries
      x-eov-operation-id: getQRCode
      x-eov-operation-handler: qr
      responses:
        '200':
          description: A list of IDs and URls
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QR'

    post:
      summary: Create a new QR code
      x-eov-operation-id: createQRCode
      x-eov-operation-handler: qr
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QRInput'
      responses:
        '201':
          description: The created QR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QR'

components:
  schemas:
    QR:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
      required:
        - id
        - url

    QRInput:
      type: object
      properties:
        url:
          type: string
      required:
        - url
