openapi: 3.0.0
info:
  title: Dynamic QR code redirection API
  version: 1.0.0
paths:

  /qrcode/{codeId}:
    get:
      summary: Go to the final location of a qr code specified by the {qrID}
      x-eov-operation-id: getQRCodeById
      x-eov-operation-handler: qr
      parameters:
        - in: path
          name: codeId
          schema:
            type: integer
          required: true
          description: Numeric ID of the QR code
      responses:
        '302':
          description: Go to the URL pointed by the QR code
        "404":
            $ref: "#/components/responses/404"

    delete:
      summary: Delete a qr code
      x-eov-operation-id: deleteQRCodeById
      x-eov-operation-handler: qr
      parameters:
        - in: path
          name: codeId
          schema:
            type: integer
          required: true
          description: Numeric ID of the QR code
      responses:
        '204':
          description: Code has been deleted
        "404":
            $ref: "#/components/responses/404"


    put:
      summary: Modify an existing QR code. If the QR code in question does not exist, one will be created
      x-eov-operation-id: updateQRCode
      x-eov-operation-handler: qr
      parameters:
        - in: path
          name: codeId
          schema:
            type: integer
          required: true
          description: Numeric ID of the QR code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QRurl'

      responses:
        '200':
          description: Modified QR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRfull'
        '201':
          description: The created QR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRfull'
        "400":
            $ref: "#/components/responses/400"
        "404":
            $ref: "#/components/responses/404"


  /qrcode:
    get:
      summary: Get all the QR entries
      x-eov-operation-id: getAllQRCodes
      x-eov-operation-handler: qr
      responses:
        '200':
          description: A list of IDs and URls
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QRfull'

    post:
      summary: Create a new QR code
      x-eov-operation-id: createQRCode
      x-eov-operation-handler: qr
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QRurl'
      responses:
        '201':
          description: The created QR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRfull'
        "400":
            $ref: "#/components/responses/400"
        "404":
            $ref: "#/components/responses/404"



                  #put:
                  #  summary: Update an existing QR code
                  #  x-eov-operation-id: updateQRCode
                  #  x-eov-operation-handler: qr
                  #  requestBody:
                  #    required: true
                  #    content:
                  #      application/json:
                  #        schema:
                  #          $ref: '#/components/schemas/QRInput'
                  #  responses:
                  #    '200':
                  #      description: Modified QR
                  #      content:
                  #        application/json:
                  #          schema:
                  #            $ref: '#/components/schemas/QR'

components:
  schemas:
    QRfull:
      type: object
      properties:
        id:
          type: number
        url:
          type: string
      required:
        - id
        - url

    QRurl:
      type: object
      properties:
        url:
          type: string
      required:
        - url

    "4xxBody":
      type: object
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            title: Error
            properties:
              message:
                type: string
      required: [errors]


  responses:
    "400":
      description: Bad request.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
    "401":
      description: Unauthorized.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
    "404":
      description: Not Found.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/4xxBody"
