name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Run docker containers
      run: docker compose -f docker-compose-cicd.yml up -d --wait
    - name: Check formatting with Prettier
      run: yarn prettier:check
    - name: Build project
      run: yarn build
    - name: Run tests
      run: yarn test

 
